apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: myapp
spec:
  containers:
  - name: my-container
    image: nginx:latest
  tolerations:
  - key: "node-role"
    operator: "Equal"
    value: "my-role"
    effect: "NoSchedule"

