apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: environment
                  operator: In
                  values:
                    - production
              - matchExpressions:
                - key: zone
                  operator: In
                  values:
                    - us-east
      containers:
        - name: my-app-container
          image: my-app-image:latest

