apiVersion: v1
kind: config 

clusters: 
  - name: production
    cluster: 
      certificate-authority: ca.cert
      server: https://192.168.10.5:6443

contexts: 
  - name: kubeadmin@production
    context: 
      cluster: production
      user: admin


users: 
  - name: kubeadmin
    user: 
       client-certificate: kubeadmin.crt
       client-key: kubeadmin.key
