apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 8080
    targetPort: 8080
  selector:
    run: nginx
  type: NodePort
endpoints:
  - addresses:
      - "192.168.49.2"
  - addresses:
      - "10.1.2.3"
