apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 1
    name: nginx
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: nginx
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: nginx
      spec:
        containers:
        - image: nginx
          name: nginx
          ports:
          - containerPort: 80
            protocol: TCP
    replicas: 1
kind: List


