apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-resource-quota
  namespaces: dev
spec:
  hard:
    pods: "10"  # Maximum number of pods in the namespace
    requests.cpu: "2"  # Maximum total CPU request (in cores)
    requests.memory: 4Gi  # Maximum total memory request
    limits.cpu: "4"  # Maximum total CPU limit (in cores)
    limits.memory: 8Gi  # Maximum total memory limit
